### ISSUE TITLE
Wrong LDFLAGS on FreeBSD

### ISSUE THREAD

**Issue by clausecker** [openhistogram/libcircllhist#67]
The `configure.ac` scripts sets up `LDFLAGS` for FreeBSD to the value

    LDFLAGS="$LDFLAGS -export-dynamic -L/usr/local/lib"

The option `-export-dynamic` is interpreted as an option `-e` (set entry point) with operand `xport-dynamic` which is nonsensical and causes spurious configure test failures.  Please patch `LDFLAGS` to use `-Wl,-E` as on other platforms instead.

**Comment by esproul** [comment]
@clausecker this should now be fixed. Thanks for the report!
